# Insert your SSID and Your PWD after inital setup
wifi: !include wifi.yaml

substitutions:
  name: lockcontrol
  friendly_name: SliderLock

esphome:
  name: $name
  platform: ESP8266
  board: d1_mini

  project:
    name: "drytoastman.lock_control"
    version: "1.0"

interval:
  - interval: 2s
    then:
      - if:
          condition:
            and:
              - api.connected
              - light.is_off: activity_led
          then:
            - light.turn_on: { id: activity_led, brightness: 30%, red: 0%, green: 0%, blue: 100% }
      - if:
          condition:
            and:
              - not: api.connected
              - light.is_on: activity_led
          then:
            - light.turn_off: activity_led


logger:
api:
ota:
text_sensor: !include statuses.yaml

button:
  - platform: restart
    name: "${friendly_name} Restart"

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic

  - platform: gpio
    name: "${friendly_name} User Request"
    pin:
      number: D1
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.toggle: { id: lock }
        - light.turn_on: { id: activity_led, brightness: 100%, red: 0%, green: 100%, blue: 0%, flash_length: 500ms }


# the relay actuation
switch:
- platform: gpio
  id: lock
  name: "${friendly_name} Lock"
  pin: D2


# Configure LED
light:
- platform: neopixelbus
  variant: WS2812
  pin: D3
  num_leds: 1
  type: GRB
  id: activity_led
  name: "${friendly_name} LED"
  restore_mode: ALWAYS_OFF
  default_transition_length: 0s
  flash_transition_length: 0s

