wifi: !include wifi.yaml

substitutions:
  name: metest
  friendly_name: TagReader
  relay_name: unconnected


globals:
  - id: led_home_red
    type: float
    restore_value: no
    initial_value: "0.0"
  - id: led_home_green
    type: float
    restore_value: no
    initial_value: "0.0"
  - id: led_home_blue
    type: float
    restore_value: no
    initial_value: "1.0"
  - id: source
    type: std::string
  - id: info
    type: std::string


script:
  - id: led_set_home
    then:
      - light.turn_on:
          id: activity_led
          brightness: 30%
          red:   !lambda return id(led_home_red);
          green: !lambda return id(led_home_green);
          blue:  !lambda return id(led_home_blue);


esphome:
  name: $name
  platform: ESP8266
  board: d1_mini

  project:
    name: drytoastman.tag_reader
    version: "1.0"

interval:
  - interval: 2s
    then:
      - if:
          condition:
            and:
              - api.connected
              - light.is_off: activity_led
          then:
            - script.execute: led_set_home
      - if:
          condition:
            and:
              - not: api.connected
              - light.is_on: activity_led
          then:
            - light.turn_off: activity_led

# Define buttons for writing tags via HA
button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: config

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  services:
  - service: tag_ok
    then:
    - rtttl.play: "upbeep:d=8,o=5,b=100:16g,b"
    - light.turn_on: { id: activity_led, brightness: 100%, red: 0%, green: 100%, blue: 0%, flash_length: 1000ms }

  - service: tag_bad
    then:
    - rtttl.play: "downbeep:d=8,o=5,b=100:16b,b4"
    - light.turn_on: { id: activity_led, brightness: 100%, red: 100%, green: 0%, blue: 0%, flash_length: 1000ms }

  - service: play_rtttl
    variables:
      song_str: string
    then:
    - rtttl.play: !lambda 'return song_str;'

  - service: write_tag_id
    variables:
      tag_id: string
    then:
    - light.turn_on: { id: activity_led, brightness: 100%, red: 100%, green: 0%, blue: 0% }
    - lambda: |-
        auto message = new nfc::NdefMessage();
        std::string uri = "https://www.home-assistant.io/tag/";
        uri += tag_id;
        message->add_uri_record(uri);
        id(pn532_board).write_mode(message);
    - rtttl.play: "writestart:d=16,o=5,b=100:b"
    - wait_until: { not: { pn532.is_writing: }}
    - script.execute: led_set_home
    - rtttl.play: "writedone:d=16,o=5,b=100:g,32_,b"

  - service: cancel_write
    then:
    - lambda: 'id(pn532_board).read_mode();'
    - script.execute: led_set_home
    - rtttl.play: "writestop:d=16,o=5,b=100:b,32_,g"

# Enable OTA upgrade
ota:

i2c:
  scan: False
  frequency: 400kHz

pn532_i2c:
  id: pn532_board
  on_tag:
    then:
    - delay: 0.05s # to fix slow component

    - lambda: |-
        id(source)="";
        id(info)="";
        if (tag.has_ndef_message()) {
          auto message = tag.get_ndef_message();
          auto records = message->get_records();
          for (auto &record : records) {
            std::string payload = record->get_payload();
            std::string type = record->get_type();
            size_t hass = payload.find("https://www.home-assistant.io/tag/");

            if (type == "U" and hass != std::string::npos ) {
              ESP_LOGD("tagreader", "Found Home Assistant tag NDEF");
              id(source)="hass";
              id(info)=payload.substr(hass + 34);
            }
            else if ( id(source)=="" ) {
              id(source)="uid";
            }
          }
        }
        else {
          id(source)="uid";
        }

    - rtttl.play: "scanned:d=8,o=5,b=100:g"
    - if:
        condition:
          lambda: 'return ( id(source)=="hass" );'
        then:
          - homeassistant.tag_scanned: !lambda 'return id(info);'
        else:
          - homeassistant.tag_scanned: !lambda |-
              ESP_LOGD("tagreader", "No HA NDEF, using UID");
              return x;


# Define the buzzer output
output:
- platform: esp8266_pwm
  pin: D7
  id: buzzer

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic

text_sensor: !include statuses.yaml

# Define buzzer as output for RTTTL
rtttl:
  output: buzzer

# Configure LED
light:
- platform: neopixelbus
  variant: WS2812
  pin: D8
  num_leds: 1
  type: GRB
  id: activity_led
  name: "${friendly_name} LED"
  restore_mode: ALWAYS_OFF
  default_transition_length: 0s
  flash_transition_length: 0s

switch:
  - platform: gpio
    id: relay
    name: "${relay_name} Switch"
    pin: D6
